<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MassTransit" Version="8.3.0" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="8.3.0" />
		<PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.3.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
		<PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="8.0.2" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="9.0.0" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.10.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.10.0-beta.1" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.10.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\OrderPlatform.Contracts\OrderPlatform.Contracts.csproj" />
	</ItemGroup>

</Project>